# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_PI(object):
    def setupUi(self, Form_PI):
        Form_PI.setObjectName("Form_PI")
        Form_PI.resize(841, 603)
        self.groupBox = QtWidgets.QGroupBox(Form_PI)
        self.groupBox.setGeometry(QtCore.QRect(700, 210, 131, 81))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 101, 22))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Form_PI)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 20, 641, 551))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 621, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Form_PI)
        QtCore.QMetaObject.connectSlotsByName(Form_PI)

    def retranslateUi(self, Form_PI):
        _translate = QtCore.QCoreApplication.translate
        Form_PI.setWindowTitle(_translate("Form_PI", "PI"))
        self.groupBox.setTitle(_translate("Form_PI", "PI_avg(%)"))
        self.groupBox_2.setTitle(_translate("Form_PI", "Peaks and Valley"))
