# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SPO2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SPO2(object):
    def setupUi(self, Form_SPO2):
        Form_SPO2.setObjectName("Form_SPO2")
        Form_SPO2.resize(715, 811)
        Form_SPO2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_4 = QtWidgets.QGroupBox(Form_SPO2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 270, 511, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 491, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Form_SPO2)
        self.pushButton.setGeometry(QtCore.QRect(560, 200, 101, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form_SPO2)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 320, 101, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(Form_SPO2)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 511, 261))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 491, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form_SPO2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 530, 511, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 491, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Form_SPO2)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 570, 161, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 19, 141, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)

        self.retranslateUi(Form_SPO2)
        QtCore.QMetaObject.connectSlotsByName(Form_SPO2)

    def retranslateUi(self, Form_SPO2):
        _translate = QtCore.QCoreApplication.translate
        Form_SPO2.setWindowTitle(_translate("Form_SPO2", "SPO2"))
        self.groupBox_4.setTitle(_translate("Form_SPO2", "Red Light"))
        self.pushButton.setText(_translate("Form_SPO2", "計算mapping"))
        self.pushButton_2.setText(_translate("Form_SPO2", "Stop scan"))
        self.groupBox.setTitle(_translate("Form_SPO2", "IR Light"))
        self.groupBox_2.setTitle(_translate("Form_SPO2", "SpO2"))
        self.groupBox_3.setTitle(_translate("Form_SPO2", "SpO2 result"))
        self.label.setText(_translate("Form_SPO2", "Avg"))
        self.label_2.setText(_translate("Form_SPO2", "Std"))
