# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_1(object):
    def setupUi(self, Form_1):
        Form_1.setObjectName("Form_1")
        Form_1.resize(931, 687)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 901, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Form_1)
        QtCore.QMetaObject.connectSlotsByName(Form_1)

    def retranslateUi(self, Form_1):
        _translate = QtCore.QCoreApplication.translate
        Form_1.setWindowTitle(_translate("Form_1", "Intensity"))
