# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_s.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_STFT(object):
    def setupUi(self, Form_STFT):
        Form_STFT.setObjectName("Form_STFT")
        Form_STFT.resize(900, 590)
        self.groupBox = QtWidgets.QGroupBox(Form_STFT)
        self.groupBox.setGeometry(QtCore.QRect(680, 80, 201, 151))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(60, 100, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form_STFT)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 40, 641, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 621, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Form_STFT)
        self.groupBox_3.setGeometry(QtCore.QRect(680, 240, 171, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 161, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form_STFT)
        QtCore.QMetaObject.connectSlotsByName(Form_STFT)

    def retranslateUi(self, Form_STFT):
        _translate = QtCore.QCoreApplication.translate
        Form_STFT.setWindowTitle(_translate("Form_STFT", "STFT"))
        self.groupBox.setTitle(_translate("Form_STFT", "STFT setting"))
        self.label.setText(_translate("Form_STFT", "Window_Size"))
        self.label_2.setText(_translate("Form_STFT", "Overlap"))
        self.pushButton.setText(_translate("Form_STFT", "Start"))
        self.groupBox_2.setTitle(_translate("Form_STFT", "Chart"))
        self.groupBox_3.setTitle(_translate("Form_STFT", "Default"))
        self.label_3.setText(_translate("Form_STFT", "Window_Size: 200"))
        self.label_4.setText(_translate("Form_STFT", "Overlap: 0.5"))
